# Ruby CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers-legacy
        environment:
          TESTOPTS: "--ci-dir=/tmp/test-results"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: "cd test/dummy && bundle exec rake db:create"
      - run: "cd test/dummy && bundle exec rake db:schema:load"

      - run:
          command: bundle exec rake test

      - store_test_results:
          path: /tmp/test-results

experimental:
  notify:
    branches:
      only:
        - master
